#The below file will run a single job targeting a machine with 16 cores andat least 
#127 GB RAM, with the shared Gluster file system, and will guarantee 72 hours of runtime.
job = RFR
universe = vanilla
log = ../logfiles/$(job)_$(Cluster).log
executable = sklearn_test.sh
#This pulls argument from last line
#arguments = $(file)
output = ../logfiles/$(job)_$(Cluster)_$(Process).out
error = ../logfiles/$(job)_$(Cluster)_$(Process).err
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = ../input/combined.tar.gz
transfer_output_files = ../output/
request_cpus = 1
request_memory = 128GB
request_disk = 2GB
requirements = (OpSysMajorVer == 6)
notification = Always
queue 1
